typography_spectrum: 0.4595291721634567
color:
  brandStrength: 0.2643731483258307
  lightness: 0.5105542012024671
  saturation: 0.17786051821894944
  rhythmicContrast: 0.8921695400495082
  brandColors:
    - '#FEFEFE'
    - '#B17551'
    - '#181319'
    - '#534D4D'
    - '#B9B5B1'
layout_spectrum: 0.5344134878832847
author:
  name: © © Tomatis® Hellas / Tomatis® Ελλάς
  email: kalostypi@icloud.com
  url: 'http://tomatishellas.com'
name: Tomatis®  Hellas / Schools
style: taylor
navigation:
  - name: Νευρο-Ακουστικά Προγράμματα-Tomatis® Hellas / Schools
    id: 692a862b-b3cb-4d5a-9e58-d994a1b0bda1
    type: content
  - name: Νευρο-Ακουστικά Προγράμματα Tomatis® από την Τomatis® Ηellas
    id: 6c175dcb-aba9-47ed-a404-0b791a967c59
    type: content
title: tomatis®  hellas / schools
description: Νευρο - Ακουστικά Προγράμματα Τomatis®
