typography_spectrum: 0.7996898822020739
color:
  brandStrength: 0.4122780286706984
  lightness: 0.5783149218186736
  saturation: 0.00857063359580934
  rhythmicContrast: 0.4991702123079449
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
layout_spectrum: 0.8151670866645873
author:
  name: '© Tomatis® Hellas - 2016 '
  email: kalostypi@icloud.com
  url: 'http://tomatishellas.com'
name: Tomatis® Hellas / Schools
navigation:
  - name: Tomatis® Hellas / Schools
    id: 692a862b-b3cb-4d5a-9e58-d994a1b0bda1
    type: content
  - name: Νευρο-Ακουστικά Προγράμματα Tomatis® Ηellas / Schools
    id: df84732d-415c-48fc-836b-f4a70464940f
    type: content
  - name: η Tomatis® Ηellas … πηγαίνει στο σχολείο!
    id: 1200aa63-6fc5-42d5-b6ef-2adfeb473a74
    type: content
  - name: ' Contact Us'
    id: ea59262d-bbd2-4411-b6ab-10a034270e26
    type: content
  - name: Τι είναι η Μέθοδος Tomatis®
    id: 91345c26-c175-4184-aed1-04f26c87868b
    type: content
title: tomatis®  hellas / schools
description: Νευρο - Ακουστικά Προγράμματα Τomatis®
