layout_spectrum: 0.8151670866645873
typography_spectrum: 0.4111018425319344
color:
  brandStrength: 0.12352592800743878
  lightness: 0.1768548241816461
  saturation: 0.6280389784369618
  rhythmicContrast: 0.5467273842077702
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
author:
  name: '© Tomatis® Hellas - 2016 '
  email: kalostypi@icloud.com
  url: 'http://tomatishellas.com'
name: Tomatis® Hellas / Schools
navigation:
  - name: Tomatis® Hellas / Schools
    id: 692a862b-b3cb-4d5a-9e58-d994a1b0bda1
    type: content
  - name: Νευρο-Ακουστικά Προγράμματα Tomatis® Ηellas / Schools
    id: df84732d-415c-48fc-836b-f4a70464940f
    type: content
  - name: η Tomatis® Ηellas … πηγαίνει στο σχολείο!
    id: 1200aa63-6fc5-42d5-b6ef-2adfeb473a74
    type: content
  - name: ' Contact Us'
    id: ea59262d-bbd2-4411-b6ab-10a034270e26
    type: content
title: tomatis®  hellas / schools
description: Νευρο - Ακουστικά Προγράμματα Τomatis®
