typography_spectrum: 0.17302524197302613
color:
  saturation: 0.2156936212603261
  brandStrength: 0.06733828676938272
  rhythmicContrast: 0.07309921215325225
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.22259209694663562
layout_spectrum: 0.770144138595661
author:
  name: '© Learning Ways Hellas / Tomatis® Hellas - 2018 '
  email: info@tomatishellas.gr
  url: 'http://tomatishellas.com'
name: 'Learning Ways Hellas / Tomatis® Hellas '
navigation:
  - name: Ψυχοπαιδαγωγικό Κέντρο LWH-TH
    id: 41ced88b-2039-4ec0-aa55-ce737e403974
    type: content
  - name: Νευρο-Κινητική Ετοιμότητα … για Μάθηση
    id: a3feec77-4748-4464-9210-a7c23141b04b
    type: content
  - name: Νευρο-Ακουστικά Προγράμματα Τomatis®
    id: 15aa7521-edae-4f12-af4e-4da0689dbbf4
    type: content
  - name: Ανακαλύψτε το ...Forbrain®
    id: 84c0f9b1-5918-4c1d-b13a-8d914c733b71
    type: content
  - name: Ανακαλύψτε το... SOUNDSORY®
    id: 951343aa-e9e3-48f2-bb30-cafcf19f0abe
    type: content
  - name: Contact Us
    id: 302545d4-2a14-4ae7-8335-b32e25435048
    type: content
  - name: 'Our blog: Με λίγα λόγια …'
    id: af2d36b9-9039-42b0-9324-ee21fcdc2625
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Learning Ways Hellas / Tomatis®  Hellas  '
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/05600811-7e41-41e4-8f60-9edf857d9ec0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/05600811-7e41-41e4-8f60-9edf857d9ec0.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Προγράμματα Νευρο-Κινητικής Ετοιμότητας για Μάθηση - NMRfL® / Νευρο-Ακουστικά
  Προγράμματα Τomatis®
purpose:
  - type: contact
    url: 'tel:+302299112171'
    label: 'Tel: +30 2299 11 21 71'
  - type: contact
    url: 'mailto:info@tomatishellas.gr'
    label: Contact us
github: true
url: 'https://tomatishellas.com/'
