typography_spectrum: 0.4595291721634567
color:
  brandStrength: 0.2643731483258307
  lightness: 0.5105542012024671
  saturation: 0.17786051821894944
  rhythmicContrast: 0.8921695400495082
  brandColors:
    - '#FEFEFE'
    - '#B17551'
    - '#181319'
    - '#534D4D'
    - '#B9B5B1'
layout_spectrum: 0.5344134878832847
author:
  name: '© Tomatis® Hellas - 2016 '
  email: kalostypi@icloud.com
  url: 'http://tomatishellas.com'
name: Tomatis®  Hellas / Schools
navigation:
  - name: Νευρο-Ακουστικά Προγράμματα Tomatis® Ηellas / Schools
    id: df84732d-415c-48fc-836b-f4a70464940f
    type: content
  - name: η Tomatis® Ηellas … πηγαίνει στο σχολείο!
    id: 1200aa63-6fc5-42d5-b6ef-2adfeb473a74
    type: content
title: tomatis®  hellas / schools
description: Νευρο - Ακουστικά Προγράμματα Τomatis®
